port: 4000
url: 'http://thinkaxelthink.github.io/feedme'
title: Shit Axel Eats
author: Axel Esquite 
exclude: [
  'index.txt',
  'js',
  'stylesheets',
  'package.json',
  'params.json.bak',
  'bower_components',
  'README.md',
  'Gemfile.lock',
  'Gemfile',
  'Gruntfile.js',
  'node_modules',
  'less'
]
